NO_TRADE_SHADOW_ONLY = "NO_TRADE_SHADOW_ONLY"
NO_TRADE_TOO_FEW_MODELS = "NO_TRADE_TOO_FEW_MODELS"
NO_TRADE_TOO_FEW_FAMILIES = "NO_TRADE_TOO_FEW_FAMILIES"
NO_TRADE_MODEL_HISTORY_INSUFFICIENT = "NO_TRADE_MODEL_HISTORY_INSUFFICIENT"
NO_TRADE_NBM_HISTORY_IMMATURE = "NO_TRADE_NBM_HISTORY_IMMATURE"
NO_TRADE_SOURCE_FROM_FUTURE = "NO_TRADE_SOURCE_FROM_FUTURE"
NO_TRADE_FORECAST_PATH_INCOMPLETE = "NO_TRADE_FORECAST_PATH_INCOMPLETE"
NO_TRADE_OBSERVATION_INVALID = "NO_TRADE_OBSERVATION_INVALID"
NO_TRADE_BOOK_INVALID = "NO_TRADE_BOOK_INVALID"
NO_TRADE_BOOK_STALE = "NO_TRADE_BOOK_STALE"
NO_TRADE_BOOK_SEQUENCE_GAP = "NO_TRADE_BOOK_SEQUENCE_GAP"
NO_TRADE_SETTLEMENT_RULES_UNVERIFIED = "NO_TRADE_SETTLEMENT_RULES_UNVERIFIED"
NO_TRADE_FEE_SCHEDULE_UNVERIFIED = "NO_TRADE_FEE_SCHEDULE_UNVERIFIED"
NO_TRADE_CAPTURE_INCOMPLETE = "NO_TRADE_CAPTURE_INCOMPLETE"
NO_TRADE_PRICE_TOO_HIGH = "NO_TRADE_PRICE_TOO_HIGH"
NO_TRADE_ROI_BELOW_HURDLE = "NO_TRADE_ROI_BELOW_HURDLE"
NO_TRADE_SPREAD_HARD_STOP = "NO_TRADE_SPREAD_HARD_STOP"
NO_TRADE_DRIFT_RISK = "NO_TRADE_DRIFT_RISK"
NO_TRADE_EVENT_EXPOSURE_LIMIT = "NO_TRADE_EVENT_EXPOSURE_LIMIT"
NO_TRADE_DAILY_LOSS_KILL = "NO_TRADE_DAILY_LOSS_KILL"
NO_TRADE_MARKET_CLOSED_OR_PAUSED = "NO_TRADE_MARKET_CLOSED_OR_PAUSED"
NO_TRADE_DUPLICATE_EVALUATION = "NO_TRADE_DUPLICATE_EVALUATION"

SHADOW_CANDIDATE_YES = "SHADOW_CANDIDATE_YES"
SHADOW_CANDIDATE_NO = "SHADOW_CANDIDATE_NO"
SHADOW_REPLACE_CANDIDATE = "SHADOW_REPLACE_CANDIDATE"
SHADOW_HOLD_EXISTING = "SHADOW_HOLD_EXISTING"
SHADOW_EXIT_FAIR_VALUE = "SHADOW_EXIT_FAIR_VALUE"

ALL_NO_TRADE_REASON_CODES = frozenset(
    {
        NO_TRADE_SHADOW_ONLY,
        NO_TRADE_TOO_FEW_MODELS,
        NO_TRADE_TOO_FEW_FAMILIES,
        NO_TRADE_MODEL_HISTORY_INSUFFICIENT,
        NO_TRADE_NBM_HISTORY_IMMATURE,
        NO_TRADE_SOURCE_FROM_FUTURE,
        NO_TRADE_FORECAST_PATH_INCOMPLETE,
        NO_TRADE_OBSERVATION_INVALID,
        NO_TRADE_BOOK_INVALID,
        NO_TRADE_BOOK_STALE,
        NO_TRADE_BOOK_SEQUENCE_GAP,
        NO_TRADE_SETTLEMENT_RULES_UNVERIFIED,
        NO_TRADE_FEE_SCHEDULE_UNVERIFIED,
        NO_TRADE_CAPTURE_INCOMPLETE,
        NO_TRADE_PRICE_TOO_HIGH,
        NO_TRADE_ROI_BELOW_HURDLE,
        NO_TRADE_SPREAD_HARD_STOP,
        NO_TRADE_DRIFT_RISK,
        NO_TRADE_EVENT_EXPOSURE_LIMIT,
        NO_TRADE_DAILY_LOSS_KILL,
        NO_TRADE_MARKET_CLOSED_OR_PAUSED,
        NO_TRADE_DUPLICATE_EVALUATION,
    }
)
